### ISSUE TITLE
OG/Twitter meta tags are useless

### ISSUE THREAD

**Issue by lunaisnotaboy** [hummingbird-me/kitsu-web#1518]
Because Ember apps are statically generated, you can't use dynamic meta tags, even if you set them after the application loads (what Kitsu currently does). This does not work for almost all sites, as they would only fetch the HTML and not execute it, therefore the meta tags are never generated.

Is this known, or is this not very important?

**Comment by NuckChorris** [comment]
We do SSR for bots, it's slow but it does mean the meta tags get to them!

**Comment by lunaisnotaboy** [comment]
Ah, okay!! thanks
