### ISSUE TITLE
[Suggestion] Official docker compose template?

### ISSUE THREAD

**Issue by GlassedSilver** [hummingbird-me/kitsu-web#1798]
I would like to suggest creating an official docker compose template. :)

**Comment by NuckChorris** [comment]
We have one, see [kitsu-tools](https://github.com/hummingbird-me/kitsu-tools), our tooling repository. It's only supported as a development setup, however, as we don't currently support federation, so there's really only intended to be one production deployment (kitsu.io itself) which uses Kubernetes (and is stored in a private repo right now)

**Comment by GlassedSilver** [comment]
Not looking to federate, just interested in running my own instance like how others run personal wikis and such.

Thank you for the pointer though!

Is AWS necessary or can it be mocked/ignored?
