### ISSUE TITLE
Kitsu.io domain expired

### ISSUE THREAD

**Issue by cpiber** [hummingbird-me/kitsu-web#2442]
Sorry if this is the wrong place to report, the discord link is invalid

According to whois, the domain expired yesterday, and starting from today, it displays only sponsors, not the Kitsu app

**Comment by Leodmanx2** [comment]
Apparently it's moved to https://kitsu.app.
![636767](https://github.com/user-attachments/assets/ae6b3ec2-8afc-4d9c-b6bd-20452faa2121)

**Comment by cpiber** [comment]
Thanks for the update, where would I find that? Is there a different discord invite somewhere?

Edit: Found it on kitsu.app in the footer, thanks

**Comment by beedell-roke** [comment]
> https://github.com/hummingbird-me/kitsu-web/issues/2442#issue-2459537413

@cpiber, this appears to be resolved.
